#!/bin/bash

echo "Checking EgressIP assignments (expecting 2 nodes)..."
echo

oc get egressip -o json | jq -r '
.items[] |
{
  name: .metadata.name,
  nodes: (
    .status.items[]?.egressIPs[]?.node
    | select(. != null)
  )
} |
.name as $name |
.nodes as $nodes |
[$nodes] |
unique |
select(length != 2) |
"EgressIP " + $name + " is assigned to " + (length|tostring) + " node(s)"
